// Tile Map for Objects in the Map
var tilemap = [
  "wH   H   H   H   H   H   H   H   Hw  H   H   H   H   H   H   H   H   H   H   H w",
  "                                                                                ",
  "w                                 w                                            w",
  "                                                                                ",
  "w                                                                              w",
  "                                  w                                             ",
  "w   k               k                B                      o                  w",
  "                                                                                ",
  "w                                 w                                            w",   
  "    K               K                                                           ",
  "w                                                                              w",
  "                                  w                                             ",
  "w                                                                              w",
  "                                                                                ",
  "w                                 w                                            w",
  "                                                                                ",
  "w                                                                              w",
  "                                  w                                             ", 
  "w                                                                              w",
  "                                                                                ",
  "w                                                                              w",
  "                                                                                ",
  "w                                                                S             w",
  "                                  w                                             ",
  "w                                                                              w",
  "                                                                                ",
  "w                                                                              w",
  "    l                 r      R    w                                             ",
  "w                                                                              w",   
  "                                                                                ",
  "w                                 w                                            w",
  "    l                                                                           ",
  "w                      b       b                                               w",
  "                                  w                                             ",
  "w                                                                              w",
  "                                   H   H   H   H   H          H   H   H  H     ",
  "w                                                                             w",
  "                                                                               ", 
  "w                                 w                                            w",
  "                                                                                ",
  "w  b    b              b    b                                                  w",
  "                                                                                 ",
  "w S                  t      t     w        H   H   H          H   H   H         w",
  "                                                                                 ",
  "w                                                                              w ",
  "                                  w                                             ",
  "w                    T      T                                                  w",
  "                                                                                ",
  "w                                 w        H   H   H          H   H   H        w",
  "                                                                                ",
  "w                       s                                                       ",
  "                                  w                                            w",
  "w                                                                               ",
  "                                                                               w",
  "h   h   h          h  h  h  h  H  w        H   H   H          H   H   H         ",
  "                                                                               w",
  "                                  w                                             ",
  "                                                                               w",
  "                                  w                                             ",
  "   v   v             v     d                w      w          w       w         w",
  "                                  w                                             ",
  "                                                                               w",
  "              q                   w         w      w          w       w         ",
  "                                                                               w",
  "                                  w                                             ",
  "                                            w      w          w       w        w",
  "   v   v             v            w                                             ",
  "                                                                               w",
  "                                  w                                              ",];


//Tile Map for collision points
var collisionmap = [
    "111111111111111111111111111111111111111                                         ",
    "1                                 1                                         mw  ",
    "11111111111111111111111111111111111111111111111111111111111111111111111111111111",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1    111111111      1111111111    1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",   
    "1                                 1  11111111111111111111    1111111111111111111",
    "1    111111111      1111111111    1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",
    "1                                 1  11111111111111111111    1111111111111111111",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1", 
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                                                              1",
    "1                                                                 111111111    1",
    "1                                                                              1",
    "1                                                                 111111111    1",
    "1                                 1                               111111111    1",
    "1                       1 1   1 111                               111111111    1",
    "1   1 1 1              11 1   1 111                               111111111    1",   
    "1                      11 1   1 111                               111111111    1",
    "1                      11 1   1 111                                111111111    1",
    "1                       1 1    1111                                            1",
    "1 1 1 1 1               1 1    1111                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1                                 1111111111111111111111       11111111111111111",
    "1                                 1111111111111111111111       111111111111111111",
    "1                                 1111111111111111111111       11111111111111111", 
    "1                                 1                                            1",
    "1                                 1                                            1",
    "111111111              b    b     1                                            1",
    "1                                 1                                            1",
    "1 S                               1        111111111111        11111111111      1",
    "1   11111111         11111  11111 1        111111111111        11111111111      1",
    "1   11111111                      1        111111111111        11111111111     1",
    "1                                 1                                            1",
    "1         11                      1                                            1",
    "1   11111 11         11111  11111 1                                            1",
    "1   11111 11                      1        111111111111        11111111111     1",
    "1   11111  1                      1        111111111111        11111111111     1",
    "1    1111111            11111     1        111111111111        11111111111                                    1",
    "1                       11111     1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "1111111111111      11111111111111111       111111111111        11111111111     1",
    "1111111111111      1111111111111111        111111111111        11111111111     1",
    "1111111111111      1111111111111111        111111111111        11111111111     1",
    "111111111111       1111111111111111                                            1",
    "1                                 1                                            1",
    "1                     1     1111  1                                            1",
    "1   1   1             1     1111  1         1      1           1      1        1",
    "1   1   1             1           1         1      1           1      1        1",
    "1   1   1      11111  1           1         1      1           1      1        1",
    "1              1   1              1         1      1           1      1        1",
    "1              1   1              1         1      1           1      1        1",
    "1              1   1              1         1      1           1      1        1",
    "1       1      1   1  1           1         1      1           1      1        1",
    "1   1   1      11111  1           1         1      1           1      1        1",
    "1   1   1             1           1         1      1           1      1        1",
    "1   1   1             1           1         1      1           1      1        1",
    "1   1   1             1           1                                            1",
    "1                                 1                                            1",
    "1                                 1                                            1",
    "11111111111111111111111111111111111111111111111111111111111111111111111111111111",];




// // To;e Map for flooring of Map
// var floormap = [
//     "wH   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H   H  ",
//     "c    c  c   c   c  c    c    c      ",
//     "w                                                                               ",
//     "                                                                                ",
//     "c    c  c   c   c  c    c    c                                                  ",
//     "                                                                                ",
//     "w                                                                               ",
//     "                                                                                ",
//     "w                                                                                 ",   
//     "c    c  c   c   c  c    c    c                                                  ",
//     "w                                                                               ",
//     "                                                                                ",
//     "w                                                                               ",
//     "                                                                                ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ", 
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
//     "wfffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
//     " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",   
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                         w   ",
//     "wfffffffffffffffffffffffffffffffffw                                             ",
//     " fffffffffffffffffffffffffffffffffw                                             ", 
//     "wfffffffffffffffffffffffffffffffffw                                             ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                              ",
//     "             ffffff                                                              ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "w            ffffff                                                             ",
//     "             ffffff                                                             ",
//     "c    c  c    ffffffc    c    c                                                  ",
//     "             ffffff                                                             ",
//     "h  h  h      ffffffh  h  h  h  h  wh   h   h   h   h                            ",
//     "             fffffff                                                            ",
//     "             fffffff              w                                             ",
//     "             fffffff                                                            ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                            ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "fffffffffffffffffffffffffffffffffff                                            ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                             ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "fffffffffffffffffffffffffffffffffff                                              ",
//     "ffffffffffffffffffffffffffffffffff                                              ",];


  var floormap = [
      "wH   H   H   H   H   H   H   H   H   H                                            ",
      "cccccccccccccccccccccccccccccceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",   
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccccccccccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", 
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
      " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeeeeeeeeeeeeeeee",
      "wfffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeeeeeeeeeeeeeeee",
      " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",   
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "cccccccccccccffffffccccccccccc     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      "wfffffffffffffffffffffffffffff     eeeeeeeeeeeeeeeeeeeewwwwwwweeeeeeeeeeeeeeeeee",
      " fffffffffffffffffffffffffffff     h   h   h   h   h  hwwwwwwwwh  h   h  h  h  h", 
      "wfffffffffffffffffffffffffffff                         wwwwwwwwwww              ",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "cccccccccccccffffffccccccccccc     FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "h  h  h      ffffffh  h  h  h  h  wFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "             fffffff               FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "             fffffff              wFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "             fffffff               FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffffffffffffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffeeeeeeefffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
      "fffffffffffffeeeeeeefffffffffffffffFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF ",];


function initializeWorldAssets()
{ 
  assets.insert('w', loadImage('Assets/Images/World/Aisle1.png'));
  assets.insert('W', loadImage('Assets/Images/World/Aisle2.png'));
  assets.insert('h', loadImage('Assets/Images/World/Aisle1_horizontal.png'));
  assets.insert('H', loadImage('Assets/Images/World/aisle2_h.png'));
  assets.insert('d', loadImage('Assets/Images/World/desk.png'));
  assets.insert('quad', loadImage('Assets/Images/World/quad1.png'));
  assets.insert('v', loadImage('Assets/Images/World/vdesk.png'));
  assets.insert('c', loadImage('Assets/Images/World/Carpet.jpg'));
  //assets.insert('f', loadImage('Assets/Images/World/floortile.jpg'));
  assets.insert('s', loadImage('Assets/Images/World/Sofaset2.png'));
  assets.insert('S', loadImage('Assets/Images/World/Sofaset3.png'));
  assets.insert('t', loadImage('Assets/Images/World/tables.png'));
  assets.insert('T', loadImage('Assets/Images/World/tables2.png'));
  assets.insert('b', loadImage('Assets/Images/World/sale.jpg'));
  assets.insert('l', loadImage('Assets/Images/World/lamps.png')); 
  assets.insert('r', loadImage('Assets/Images/World/roundtable.png')); 
  assets.insert('R', loadImage('Assets/Images/World/table1.png')); 
  assets.insert('k', loadImage('Assets/Images/World/kitchen1.png'));
  assets.insert('K', loadImage('Assets/Images/World/kitchen2.png'));
  assets.insert('B', loadImage('Assets/Images/World/beds.png'));
  assets.insert('o', loadImage('Assets/Images/World/ottomans.png'));


  //Front Running Frames
  assets.insert('mc1', loadImage('Assets/Images/World/mcfront.png'));
  assets.insert('mc12', loadImage('Assets/Images/World/mcfront2.png'))
  assets.insert('mc13', loadImage('Assets/Images/World/mcfront3.png'))
  // Back Running ANimation
  assets.insert('mc2', loadImage('Assets/Images/World/mcback.png'));
  assets.insert('mc22', loadImage('Assets/Images/World/mcback2.png'));
  assets.insert('mc23', loadImage('Assets/Images/World/mcback3.png'));
  //left
  assets.insert('mc3', loadImage('Assets/Images/World/mcleft.png'));
  assets.insert('mc32', loadImage('Assets/Images/World/mcleft2.png'));
  assets.insert('mc33', loadImage('Assets/Images/World/mcleft3.png'));
  //right
  assets.insert('mc4', loadImage('Assets/Images/World/mcright.png'));
  assets.insert('mc42', loadImage('Assets/Images/World/mcright2.png'));
  assets.insert('mc43', loadImage('Assets/Images/World/mcright3.png'));
}
