// Tile Map for Objects in the Map
var tilemap = [
  "wH   H   H   H   H   H   H   H   Hw  H                                          ",
  "                                                                             w  ",
  "w                                 w                                             ",
  "                                                                                ",
  "w                                                                               ",
  "                                  w                                             ",
  "w                                                                               ",
  "                                                                                ",
  "w                                 w                                             ",   
  "                                                                                ",
  "w                                                                               ",
  "                                  w                                             ",
  "w                                                                               ",
  "                                                                                ",
  "w                                 w                                             ",
  "                                                                                ",
  "w                                                                               ",
  "                                  w                                             ", 
  "w                                                                               ",
  "                                                                                ",
  "w                                                                               ",
  "                                                                                ",
  "w                                                                               ",
  "                                  w                                             ",
  "w                                                                               ",
  "                                                                                ",
  "w                                                                               ",
  "                                  w                                            ",
  "w                                                                               ",   
  "                                                                                ",
  "w                                 w                                             ",
  "                                                                                ",
  "w                                                                               ",
  "                                                                                ",
  "w                                                                               ",
  "                                                                            w   ",
  "w                                                                               ",
  "                                                                               ", 
  "w                                 w                                             ",
  "                                                                                ",
  "w  b    b              b    b                                                   ",
  "                                                                                 ",
  "w S                  t      t     w                                             ",
  "                                                                                 ",
  "w                                                                                ",
  "                                  w                                             ",
  "w                    T      T                                                   ",
  "                                                                                ",
  "w                                 w                                            ",
  "                                                                                ",
  "w                       s                                                       ",
  "                                  w                                             ",
  "w                                                                               ",
  "                                                                                ",
  "h   h   h          h  h  h  h  h  wh   h   h   h   h                            ",
  "                                                                                ",
  "                                  w                                             ",
  "                                                                                ",
  "                                  w                                             ",
  "   v   v             v     d                                                    ",
  "                                  w                                             ",
  "                                                                                ",
  "              q                   w                                             ",
  "                                                                                ",
  "                                  w                                             ",
  "                                                                                ",
  "   v   v             v            w                                             ",
  "                                                                                ",
  "                                  w                                              ",];


//Tile Map for collision points
var collisionmap = [
    "111111111111111111111111111111111111111                                         ",
    "1                                                                            w  ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",   
    "1                                                                               ",
    "1                                                                               ",
    "1                                                                               ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ", 
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                                                              ",
    "1                                                                              ",
    "1                                                                              ",
    "1                                                                              ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",   
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1                                                                           w   ",
    "1                                                                               ",
    "1                                                                               ", 
    "1                                                                               ",
    "1                                 1                                             ",
    "111111111              b    b     1                                             ",
    "1                                 1                                             ",
    "1 S                               1                                             ",
    "1   11111111         11111  11111 1                                            ",
    "1   11111111                      1                                             ",
    "1                                 1                                             ",
    "1         11                      1                                             ",
    "1   11111 11         11111  11111 1                                             ",
    "1   11111 11                      1                                             ",
    "1   11111  1                      1                                             ",
    "1    1111111            11111     1                                             ",
    "1                       11111     1                                             ",
    "1                                 1                                             ",
    "1                                 1                                             ",
    "1111111111111      11111111111111111111111111111111111                          ",
    "1111111111111      1111111111111111                                             ",
    "1111111111111      1111111111111111                                             ",
    "111111111111       1111111111111111                                             ",
    "1                                 1                                             ",
    "1  11  11            11     111   1                                             ",
    "1  11  11            11     111   1                                             ",
    "1  11  11            11           1                                             ",
    "1  11  11     111111 11           1                                             ",
    "1             1    1              1                                             ",
    "1             1    1              1                                             ",
    "1             1    1              1                                             ",
    "1  11  11     1    1 11           1                                             ",
    "1  11  11     111111 11           1                                             ",
    "1  11  11            11           1                                              ",
    "1  11  11            11           1                                              ",
    "1  11  11            11           1                                              ",
    "1                                 1                                              ",
    "1                                 1                                              ",];




// To;e Map for flooring of Map
var floormap = [
    "wH   H   H   H   H   H   H   H   H   H                                          ",
    "c    c  c   c   c  c    c    c                                               w  ",
    "w                                                                               ",
    "                                                                                ",
    "c    c  c   c   c  c    c    c                                                  ",
    "                                                                                ",
    "w                                                                               ",
    "                                                                                ",
    "w                                                                                 ",   
    "c    c  c   c   c  c    c    c                                                  ",
    "w                                                                               ",
    "                                                                                ",
    "w                                                                               ",
    "                                                                                ",
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ", 
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
    "wfffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
    " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",   
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "c    c  c    ffffffc    c    c                                                  ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "             ffffff                                                         w   ",
    "wfffffffffffffffffffffffffffffffffw                                             ",
    " fffffffffffffffffffffffffffffffffw                                             ", 
    "wfffffffffffffffffffffffffffffffffw                                             ",
    "c    c  c    ffffffc    c    c                                                  ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ",
    "w            ffffff                                                              ",
    "             ffffff                                                              ",
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ",
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "w            ffffff                                                             ",
    "             ffffff                                                             ",
    "c    c  c    ffffffc    c    c                                                  ",
    "             ffffff                                                             ",
    "h  h  h      ffffffh  h  h  h  h  wh   h   h   h   h                            ",
    "             fffffff                                                            ",
    "             fffffff              w                                             ",
    "             fffffff                                                            ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                            ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                            ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                             ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                              ",
    "fffffffffffffffffffffffffffffffffff                                              ",];


  var floormap = [
      "wH   H   H   H   H   H   H   H   H   H                                          ",
      "cccccccccccccccccccccccccccccc                                               w  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",   
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccccccccccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ", 
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
      "wfffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
      " fffffffffffffffffffffffffffffffffwwwwwwwwwwwwwwwwwwwwwwwwwwwww                 ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",   
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                              w   ",
      "wfffffffffffffffffffffffffffffffffw                                             ",
      " fffffffffffffffffffffffffffffffffw                                             ", 
      "wfffffffffffffffffffffffffffffffffw                                             ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "cccccccccccccffffffccccccccccc                                                  ",
      "h  h  h      ffffffh  h  h  h  h  wh   h   h   h   h                            ",
      "             fffffff                                                            ",
      "             fffffff              w                                             ",
      "             fffffff                                                            ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",
      "fffffffffffffffffffffffffffffffffff                                             ",];


function initializeWorldAssets()
{ 
  assets.insert('w', loadImage('Assets/Images/World/Aisle1.png'));
  assets.insert('W', loadImage('Assets/Images/World/Aisle2.png'));
  assets.insert('h', loadImage('Assets/Images/World/Aisle1_horizontal.png'));
  assets.insert('H', loadImage('Assets/Images/World/aisle2_h.png'));
  assets.insert('d', loadImage('Assets/Images/World/desk.png'));
  assets.insert('quad', loadImage('Assets/Images/World/quad1.png'));
  assets.insert('v', loadImage('Assets/Images/World/vdesk.png'));
  assets.insert('c', loadImage('Assets/Images/World/Carpet.jpg'));
  //assets.insert('f', loadImage('Assets/Images/World/floortile.jpg'));
  assets.insert('s', loadImage('Assets/Images/World/Sofaset2.png'));
  assets.insert('S', loadImage('Assets/Images/World/Sofaset3.png'));
  assets.insert('t', loadImage('Assets/Images/World/tables.png'));
  assets.insert('T', loadImage('Assets/Images/World/tables2.png'));
  assets.insert('b', loadImage('Assets/Images/World/sale.jpg'));
  assets.insert('l', loadImage('Assets/Images/World/lamps.png')); 

  assets.insert('mc1', loadImage('Assets/Images/World/mcfront.png'));
  assets.insert('mc2', loadImage('Assets/Images/World/mcback.png'));
  assets.insert('mc3', loadImage('Assets/Images/World/mcleft.png'));
  assets.insert('mc4', loadImage('Assets/Images/World/mcright.png'));
}
